on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        type: choice
        options:
        - stage
        - beta
        - prod
      version:
        description: 'Test scenario tags'
        required: true 
        type: string

jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2.4.0
        with:
          ref: refs/tags/${{ github.event.inputs.version }}
#       - run: git checkout tags/${VERSION}
#         env:
#           VERSION: ${{ github.event.inputs.version }}

      - run: git branch

      - run: cat README.md
      - run: |
          echo "Environment: $ENVIRONMENT"
          echo "Version: $VERSION"
          if [ ${ENVIRONMENT} == "prod" ] ; then
            echo "prod environment is selected"
          else
            echo "${ENVIRONMENT} is selected"
          fi
        env:
          ENVIRONMENT: ${{ github.event.inputs.environment }}
          VERSION: ${{ github.event.inputs.version }}
