on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        type: choice
        options:
        - stage
        - beta
        - prod
      version:
        description: 'Test scenario tags'
        required: true 
        type: string

jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Environment: $ENVIRONMENT"
          echo "Version: $VERSION"
        env:
          ENVIRONMENT: ${{ github.event.inputs.environment }}
          VERSION: ${{ github.event.inputs.version }}