name: PR Tag Release
on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  tag-release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Triggering Deployment
        run: |
          curl -X POST -H "Authorization:Bearer ${{ secrets.GH_API_TOKEN }}" ${{ secrets.DISPATCH_URL }} -d '${{ secrets.INPUTS }}'
