name: PR Tag Release
on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  tag-release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Triggering Deployment
        run: |
          curl -X POST -H "Accept: application/vnd.github.v3+json" -H "Authorization:Bearer ${{ secrets.GH_API_TOKEN }}" https://api.github.com/repos/macnev2013/wf-dispatch-gh-action/actions/workflows/deploy.yml/dispatches -d '{"ref":"main", "inputs": { "logLevel":"info", "tags":"false" }}'
