name: Execute Tests
on:
  push:
    - main
  workflow_dispatch:

jobs:

  goat-prepare:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Terraform AWS Provider
      uses: actions/checkout@v3
      with:
        repository: hashicorp/terraform-provider-aws
        path: './terraform-provider-aws'

    - name: Get Release Date
      run: |
        echo "RELEASE_DATE=`date '+%Y-%m-%d-%H-%M-%S'`" >> $GITHUB_ENV

    - name: Print Release Date
      run: |
        echo "$RELEASE_DATE"

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.RELEASE_DATE }}
        release_name: Release ${{ env.RELEASE_DATE }}
        draft: false
        prerelease: false

    - name: Create Zip file
      run: |
        zip -r skaff.zip ./terraform-provider-aws/skaff
        zip -r names.zip ./terraform-provider-aws/names

    - name: Upload Release Asset
      id: upload-release-asset-0
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./skaff.zip
        asset_name: skaff.zip
        asset_content_type: application/zip

    - uses: DamianReeves/write-file-action@master
      with:
        path: ./release-details.txt
        contents: |
          ${{ steps.create_release.outputs.upload_url }}
        write-mode: overwrite

    - name: Archive artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Releaes
        path: |
          ./release-details.txt


  upload-from-other-job:

    name: Artifact Upload
    runs-on: ubuntu-latest
    needs: goat-prepare

    steps:

    - name: Download math result for job 2
      uses: actions/download-artifact@v3
      with:
        name: Releaes

    - name: Get Release Details
      run: |
        echo "RELEASE_DETAILS=`cat release-details.txt`" >> $GITHUB_ENV
        zip -r a.zip release-details.txt

    - name: Upload Release Asset
      id: upload-release-asset-1
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ env.RELEASE_DETAILS }}
        asset_path: ./a.zip
        asset_name: a.zip
        asset_content_type: application/zip